In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 30)
pd.set_option('display.float_format', '{:.4f}'.format)

In [2]:
df_brand = pd.read_csv('../data/raw/brand_metadata.csv')
df_brand

,BRAND_ID,PUBLISHER_UUID,BRAND_NAME,PRIMARY_CATEGORY,SUBCATEGORIES,DESCRIPTION
0,4313,b6f8dbb2-3e80-4126-8a68-fc2f8130b526,Lumen Carry,Apparel & Accessories,"[\n ""Diaper Bags & Carriers"",\n ""Other Appar...",Bags built for people getting the most out of ...
1,2208,b7dea133-983b-4e7b-8fac-b18d88340882,Greenfield Pantry,Food & Beverage,"[\n ""Food"",\n ""Snacks"",\n ""Beverage"",\n ""K...",Organic snacks and meals for babies to big kids.
2,5124,739078ad-43e5-4f4d-aa8f-25cdb0030f2f,CardCompare,Finance,"[\n ""Credit Cards""\n]",A financial comparison service for everyday bo...
3,2165,da9c1172-323c-490e-b9f7-2249703c1d00,Reusabag,Home & Kitchen,"[\n ""Gear"",\n ""Food Storage & Organization""\n]","The simple, reusable alternative to plastic bags."
4,5427,3b2a9c7f-b856-4eaf-ad9b-d1eb0bee90a1,Northpoint Skate,Apparel & Accessories,"[\n ""Kid's Footwear"",\n ""Women's Accessories...","Skate-inspired footwear, apparel and accessories."
...,...,...,...,...,...,...
337,5240,9bef125b-ea76-4d46-a087-30720e7c5cf4,Henley 1909,Home & Kitchen,"[\n ""Drinkware""\n]",Discover the official online store of Henley 1...
338,5200,17ed82df-7059-4fab-befb-8b8f76e0d322,AURUM,Apparel & Accessories,"[\n ""Jewelry & Watches""\n]",The number-one choice for men's everyday jewelry.
339,5399,b0485362-676a-401e-9430-685728f5f8aa,FreckledPoppy,Apparel & Accessories,"[\n ""Women's Footwear"",\n ""Women's Apparel"",...","A women's boutique with playful, modern fashio..."
340,5293,0bc82e1f-13d4-4994-a35a-1403806eb096,Compass - Nifty,Media & Entertainment,"[\n ""Software & Apps""\n]",An all-in-one money-management app.
341,1881,6af970be-e473-47de-aec8-720014d33aa4,Kohi,Apparel & Accessories,"[\n ""Women's Footwear"",\n ""Men's Footwear""\n]",Where thoughtful design meets sustainable craf...

In [3]:
df_events = pd.read_csv('../data/raw/events_train.csv')
df_events

,SESSION_ID,SESSION_START_AT_UTC,IDENTITY_UUID,PUBLISHER_NAME,PUBLISHER_UUID,BRAND_NAME,BRAND_ID,PAGE_TYPE,WIDGET_TYPE,WIDGET_VERSION,OS_CLASS,BRAND_DISPLAY_PLACEMENT,CUSTOM_METADATA,CLICKED,CONVERTED
0,4f45ecb3-f940-42fc-a8c6-54ca0c734f43,2026-04-16 00:18:45.144+00,51d0f7db-d74a-4639-8202-7ab86349197a,BookFit,f8d1dab3-604d-48ef-ba42-6dca38a86d63,HumaneNet,5117,ORDER_STATUS,APP_NATIVE_ESSENTIAL,0.2000,Mobile,INLINE,"{\n ""transaction_type"": ""booking""\n}",False,False
1,b20c87f8-05c4-4103-9fec-adc2bc7af183,2026-04-16 01:12:12.026+00,047aba5efa4159a6,Wild X Verity,26bead2c-49f9-45f4-9de9-07f25a8db44b,Bonus.com,5085,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,PULLUP,{},False,False
2,af103558-69e4-4f52-a9df-9f99312b6535,2026-04-16 02:53:35.691+00,fe6a256dd0ac932e,Driftbooks,a65146e9-b04e-4a45-8cc0-54fafe1b8e88,Bonus.com,5085,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,INLINE,"{\n ""shipping_method"": ""Standard Shipping""\n}",False,False
3,678c9848-5305-4ac1-a643-17c4873bd271,2026-04-16 02:07:17.719+00,1cd47270-7e2c-4f0a-b978-03e595b7d7a9,Wanderfeet,468d4148-4f8e-4a70-b96a-62783aabec3e,ShipFree.com,5073,ORDER_STATUS,SHOPIFY_NATIVE_ESSENTIAL,0.2000,Mobile,INLINE,{},False,False
4,a9a4af35-5493-4d5f-8961-ecaf7b2682ba,2026-04-16 01:56:30.462+00,b9a0cefb5814c4c6,Sirena Intimates,e99c91ab-bf3e-495b-88d7-850436990761,Bonus.com,5085,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,PULLUP,{},False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471671,1f69dae4-e69b-41c9-a6a3-d8f4e110c95a,2026-03-10 13:54:37.243+00,18fabb6be70fc1b6,Pursuit Cyclist,4940d675-ed11-4808-8994-be4def6c8661,CardCompare,5124,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,PULLUP,{},False,False
471672,59e5b0ab-9c43-4d9b-973e-7dd267ca2658,2026-03-10 23:59:54.357+00,c2748c36f64c4ed5,DSL,ec784669-c008-4553-a029-b298cef7a984,ShipFreebie,5149,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,INLINE,{},False,False
471673,7add2ff3-e435-498b-a3b8-183a55bd02a3,2026-03-10 19:35:05.591+00,51cce99077d14d08,Ironwood Trading Co.,37e5e48b-97b2-4312-a51b-3a490b405fef,DropDelivery,5205,ORDER_TRACKING,APP_NATIVE_ESSENTIAL,0.2000,Mobile,PULLUP,{},False,False
471674,be12997c-a0db-405c-9c9e-a9f3466edc9a,2026-04-15 17:14:33.893+00,3b0e2afa-2de1-407d-854a-1a90612bc99c,Crown Atelier,0f655c94-5aea-4d62-85c3-f43f6f26ba77,FreshFork,5449,THANK_YOU,SHOPIFY_NATIVE_ESSENTIAL,0.2000,Mobile,INLINE,{},False,False
471675,917cce7f-9765-4da7-80de-eba0d8cbb14a,2026-04-15 00:33:45.878+00,7dd9df21-a9a3-459a-a5a5-247c803b06e5,Cozy Hearth,7b5c24f6-1f71-4018-8c54-8a3e673a6bef,Mag Snap,5305,THANK_YOU,SHOPIFY_NATIVE_ESSENTIAL,0.2000,Desktop,INLINE,{},False,False

In [4]:
df_events['WIDGET_TYPE'].value_counts(dropna=False)

WIDGET_TYPE
APP_NATIVE_ESSENTIAL        388937
SHOPIFY_NATIVE_ESSENTIAL     54855
ESSENTIAL                    25816
SHOPIFY_NATIVE_LEAD_GEN       1157
APP_NATIVE_BRAND_VISUAL        892
LEAD_GEN                        19
Name: count, dtype: int64

In [5]:
df_events['WIDGET_VERSION'].value_counts(dropna=False)

WIDGET_VERSION
0.2000    426064
0.1000     34479
0.3000      9957
0.5100      1157
0.5500        19
Name: count, dtype: int64

In [6]:
df_events['OS_CLASS'].value_counts(dropna=False)

OS_CLASS
Mobile     398990
Desktop     55936
Unknown     16632
Cloud         105
Hacker         13
Name: count, dtype: int64